language: python
dist: trusty
sudo: required
cache:
  pip: true
  directories:
    - bin/sources/

python:
- 2.7

before_install:
 - date

install:
 - bash ./install.sh

script:
 - wxtoimg -h
 - sox --version
 - lame --version
 - wxtoimg -V
 - wxmap -V
 - convert -help
 - ./genpasstable.py
